name: splat
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - plyfile
  - tqdm
  - pytorch
  - torchaudio
  - torchvision
  # Change to version number that best fits your CUDA version found from nvidia-smi
  # There can be a compilation problem if nvidia-cuda-toolkit is already installed in your system
  # See if 'nvcc -V' gives you a version # in the command line
  - pytorch::pytorch-cuda=12.1
  - nvidia::cuda-nvcc=12.1
  - nvidia::cuda-toolkit=12.1
  - nvidia::cuda-runtime=12.1
  - conda-forge::ninja
  - conda-forge::glm
  - conda-forge::glew
  - conda-forge::mesa

  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn