name: splat
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge

dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  # Change to version number that best fits your CUDA version found from nvidia-smi
  # There can be a compilation problem if nvidia-cuda-toolkit is already installed in your system
  # See if 'nvcc -V' gives you a version # in the command line
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - cuda-nvcc=11.8
  - cuda-python=11.8
  - cmake
  - ninja
  - ceres-solver
  - cgal
  - flann
  - freeimage
  - glm
  - glew
  - gmp
  - mesa
  - metis
  - mpfr
  - pcl
  - pyopengl
  - opencv
  - libopencv
  - av
  - ffmpeg
  - libboost
  - libgdal
  - libglu
  - libgomp
  - lz4-c
  - sqlite
  - suitesparse
  - pip
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - rembg[cli]