name: splat
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - pytorch=*=*cuda11.7*
  - torchvision=*=*cu117*
  - torchaudio=*=*cu117*
  - cudatoolkit=11.7
  - plyfile
  - tqdm
  - pip
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn