name: gaussian_splatting
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - plyfile
  - tqdm
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.1
  - nvidia::cuda-toolkit=12.1

  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn